services:
  - name: market-analyzer
    env:
      - name: FLASK_APP
        value: "app.py"
      - name: FLASK_ENV
        value: "production"
      - name: PYTHON_VERSION
        value: "3.9.18"
    build:
      args:
        - BP_GO_VERSION=1.20.*
        - BP_GO_TARGETS=./cmd/...
    ports:
      - port: 5001
        http: {}
    routes:
      - path: /
        port: 5001
    scaling:
      min: 1
      max: 1
    instances:
      type: nano
    healthchecks:
      http:
        path: /
        port: 5001
        initial_delay: 30
        period: 10
        success_threshold: 1
        failure_threshold: 3
